#!/usr/bin/env python3
"""Build the Supplementary Materials docx: every CSV/table/plot generated during
this analysis that is NOT reproduced in the main manuscript, each with a short
description, so nothing from the project is undocumented."""

import os
import pandas as pd
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

BASE = r"C:\Users\SAMSUNG\Desktop\project2"
FIG = os.path.join(BASE, "figures")
RES = os.path.join(BASE, "results")
OUT = os.path.join(BASE, "manuscript", "supplementary_materials.docx")

doc = Document()
style = doc.styles["Normal"]
style.font.name = "Times New Roman"
style.font.size = Pt(10.5)
style.paragraph_format.space_after = Pt(6)
style.paragraph_format.line_spacing = 1.1

for level, size in [(1, 14), (2, 12), (3, 11)]:
    hs = doc.styles[f"Heading {level}"]
    hs.font.name = "Times New Roman"
    hs.font.size = Pt(size)
    hs.font.bold = True
    hs.font.color.rgb = RGBColor(0, 0, 0)
    hs.paragraph_format.space_before = Pt(12)
    hs.paragraph_format.space_after = Pt(5)


def set_cell_shading(cell, hex_color):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def add_df_table(df, font_size=8, max_col_width=1.3):
    n_cols = len(df.columns)
    table = doc.add_table(rows=1, cols=n_cols)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for i, col in enumerate(df.columns):
        hdr[i].text = ""
        run = hdr[i].paragraphs[0].add_run(str(col))
        run.bold = True
        run.font.size = Pt(font_size)
        set_cell_shading(hdr[i], "D9D9D9")
    for _, row in df.iterrows():
        cells = table.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = ""
            if isinstance(val, float):
                txt = f"{val:.4g}"
            else:
                txt = str(val)
            run = cells[i].paragraphs[0].add_run(txt)
            run.font.size = Pt(font_size)
    doc.add_paragraph().paragraph_format.space_after = Pt(2)
    return table


def add_caption(text, bold_prefix=None):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(3)
    p.paragraph_format.space_after = Pt(10)
    if bold_prefix:
        r = p.add_run(bold_prefix)
        r.bold = True
        r.font.size = Pt(9.5)
    r2 = p.add_run(text)
    r2.font.size = Pt(9.5)
    r2.italic = True


def add_figure(path, width_in=5.5):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run()
    run.add_picture(path, width=Inches(width_in))


def csv_table(relpath, font_size=8, drop_cols=None, round_cols=None):
    df = pd.read_csv(os.path.join(RES, relpath))
    if drop_cols:
        df = df.drop(columns=[c for c in drop_cols if c in df.columns])
    if round_cols:
        for c in round_cols:
            if c in df.columns:
                df[c] = df[c].astype(float).round(4)
    add_df_table(df, font_size=font_size)


# =====================================================================
# TITLE
# =====================================================================
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run(
    "Supplementary Materials\n"
    "HSF2 Expression Is Inversely, Not Positively, Associated with a "
    "NETosis-Core Gene Signature Across Liver and Lung Fibrosis"
)
r.bold = True
r.font.size = Pt(14)
title.paragraph_format.space_after = Pt(18)

doc.add_paragraph(
    "This document reports every intermediate and final data table, statistical result, and "
    "figure generated for the accompanying manuscript that is not reproduced in the main text, "
    "so that the full analysis is documented and independently checkable. All items are also "
    "available as machine-readable CSV files and high-resolution PNG figures in the project's "
    "version-controlled repository (GitHub: bioinform25/project2, folders results/ and figures/), "
    "generated by the numbered R scripts in scripts/ (00-12). Very large per-sample data tables "
    "(hundreds of rows) are described here with summary statistics and referenced by file name "
    "rather than reproduced row-by-row; the full CSV is available in the repository."
)
doc.add_paragraph(
    "Contents: Section S1 (fibrosis cohorts, full statistics), Section S2 (individual NETosis "
    "panel gene results per cohort), Section S3 (ChEA3 in silico enrichment, full output), "
    "Section S4 (HCC immune-checkpoint-inhibitor cohorts, full statistics), Section S5 "
    "(supplementary figures: all cohort-level scatter and boxplots not shown in the main text)."
)
doc.add_page_break()

# =====================================================================
# S1. FIBROSIS COHORTS - FULL STATISTICS
# =====================================================================
doc.add_heading("S1. Fibrosis cohorts: full statistics", level=1)

doc.add_heading("Table S1a. Primary endpoint results, all 4 fibrosis cohorts, full statistics "
                 "including bootstrap CI and leave-one-out (LOO) sensitivity range.", level=3)
add_caption(
    "Source: results/ALL_COHORTS_primary_endpoint_summary.csv. Corresponds to main-text Table 2, "
    "shown here with organ/comparison labels and full precision.")
csv_table("ALL_COHORTS_primary_endpoint_summary.csv", font_size=7)

doc.add_heading("Table S1b. Random-effects meta-analysis summary (overall and organ-restricted).",
                 level=3)
add_caption("Source: results/ALL_COHORTS_meta_analysis_summary.csv.")
csv_table("ALL_COHORTS_meta_analysis_summary.csv", font_size=8)

doc.add_heading("Table S1c. Specificity control: HSF2/NET_core/PTPRC pairwise correlations, "
                 "full statistics with bootstrap CI and LOO range.", level=3)
add_caption("Source: results/SPECIFICITY_check_PTPRC_vs_NETcore.csv. Corresponds to main-text "
            "Table 3, shown here with full precision and LOO sensitivity range.")
csv_table("SPECIFICITY_check_PTPRC_vs_NETcore.csv", font_size=7)

doc.add_heading("Table S1d. Per-sample gene detection rate, GSE135251 (RNA-seq), NETosis panel "
                 "genes.", level=3)
add_caption(
    "Source: results/liver_GSE135251_gene_detection_rate.csv. Fraction of the 216 samples with "
    "a nonzero raw count for each panel gene; reported because several NETosis-lineage genes are "
    "lowly and sparsely expressed in bulk liver tissue (neutrophils are a minor fraction of the "
    "cell mixture), which is expected biology rather than a quality defect, but is relevant to "
    "interpreting the strength of individual-gene correlations.")
csv_table("liver_GSE135251_gene_detection_rate.csv", font_size=9)

# =====================================================================
# S2. INDIVIDUAL GENE RESULTS PER COHORT
# =====================================================================
doc.add_heading("S2. Individual NETosis-panel gene results per cohort", level=1)
doc.add_paragraph(
    "Full per-gene Spearman correlation with HSF2 (bootstrap CI, LOO range, BH-FDR-adjusted "
    "p-value) for every gene in the NETosis-extended panel, in each of the four fibrosis cohorts "
    "individually. The cross-cohort summary derived from these tables is main-text Table 4 "
    "(abbreviated) and Table S2e (full, below)."
)

s2_files = [
    ("GSE135251 (liver, primary)", "liver_GSE135251_individual_gene_results.csv"),
    ("GSE14323 (liver, replication)", "liver_GSE14323_individual_gene_results.csv"),
    ("GSE47460 (lung, primary)", "lung_GSE47460_individual_gene_results.csv"),
    ("GSE53845 (lung, replication)", "lung_GSE53845_individual_gene_results.csv"),
]
for label, fname in s2_files:
    doc.add_heading(f"Table S2. {label}: individual-gene results.", level=3)
    add_caption(f"Source: results/{fname}.")
    csv_table(fname, font_size=7)

doc.add_heading("Table S2e. Cross-cohort gene consistency, full 12-gene table.", level=3)
add_caption(
    "Source: results/CROSS_COHORT_gene_consistency.csv. Corresponds to main-text Table 4 "
    "(which shows only the 5 most reproducible genes); this table includes all 12 NETosis-panel "
    "genes tested (AZU1 tested in 3/4 cohorts only - no probe/gene match on the GSE47460 "
    "platform).")
csv_table("CROSS_COHORT_gene_consistency.csv", font_size=6.5)

# =====================================================================
# S3. CHEA3 FULL OUTPUT
# =====================================================================
doc.add_heading("S3. ChEA3 in silico transcription-factor enrichment: full output", level=1)
doc.add_paragraph(
    "HSF2 rank, total transcription factors ranked, gene overlap (intersect), FDR, and odds "
    "ratio, extracted from every ChEA3 evidence library in which HSF2 was returned, for all "
    "three queried gene sets. Corresponds to main-text Table 5 (which shows only the "
    "NET_core_consistent query)."
)
doc.add_heading("Table S3. ChEA3 full results, all 3 queries.", level=3)
add_caption("Source: results/CHEA3_HSF2_enrichment_results.csv. NET_core_consistent = "
            "PADI4/ELANE/MPO/CAMP/DEFA4; NET_organ_divergent = LTF/NCF2/ITGAM/LCN2; "
            "NET_core_only = PADI4/ELANE/MPO (the original pre-specified panel).")
csv_table("CHEA3_HSF2_enrichment_results.csv", font_size=7)

# =====================================================================
# S4. HCC-ICI COHORTS FULL STATISTICS
# =====================================================================
doc.add_heading("S4. HCC immune-checkpoint-inhibitor cohorts: full statistics", level=1)

doc.add_heading("Table S4a. Pooled HCC-ICI HSF2 summary with random-effects meta-analysis.",
                 level=3)
add_caption("Source: results/hcc_ICI_POOLED_HSF2_with_meta.csv. Corresponds to main-text Table 6.")
csv_table("hcc_ICI_POOLED_HSF2_with_meta.csv", font_size=8)

ici_cohorts = [
    ("GSE215011", "anti-PD-1 monotherapy (nivolumab), n=10"),
    ("GSE279750", "anti-PD-L1 combination, post-treatment, n=10"),
    ("GSE235863", "anti-PD-1 + lenvatinib combination, post-treatment, n=15"),
]
for acc, desc in ici_cohorts:
    doc.add_heading(f"Table S4. {acc} ({desc}): group comparison "
                     "(HSF2 / NET_core / NET_extended, responder vs. non-responder).", level=3)
    add_caption(f"Source: results/hcc_ICI_{acc}_group_comparison.csv.")
    csv_table(f"hcc_ICI_{acc}_group_comparison.csv", font_size=8)

    doc.add_heading(f"Table S4. {acc}: HSF2 vs. NET_core correlation (all tumors).", level=3)
    add_caption(f"Source: results/hcc_ICI_{acc}_HSF2_vs_NETcore.csv.")
    csv_table(f"hcc_ICI_{acc}_HSF2_vs_NETcore.csv", font_size=8)

    df = pd.read_csv(os.path.join(RES, f"hcc_ICI_{acc}_sample_level_data.csv"))
    doc.add_paragraph(
        f"Full per-patient sample-level data for {acc} (n={len(df)} tumors; columns: sample/"
        f"patient ID, response group, HSF2, NET_core, NET_extended expression) is available in "
        f"results/hcc_ICI_{acc}_sample_level_data.csv in the repository and is not reproduced "
        f"row-by-row here."
    )

# =====================================================================
# S5. SUPPLEMENTARY FIGURES
# =====================================================================
doc.add_page_break()
doc.add_heading("S5. Supplementary Figures", level=1)
doc.add_paragraph(
    "Cohort-level scatter plots (HSF2 vs. NET_core score) and boxplots (HSF2 across disease "
    "groups/stages) for every individual cohort. The multi-cohort forest-plot summaries of these "
    "same data are shown as Figures 1-2 in the main text."
)

sfigs = [
    ("liver_GSE135251_HSF2_by_stage.png", "S1", "GSE135251 (liver): HSF2 expression across "
     "histological fibrosis stage (0-4)."),
    ("liver_GSE135251_HSF2_vs_NETcore.png", "S2", "GSE135251 (liver, NAFLD subset, n=206): "
     "HSF2 vs. NET_core score scatter plot with linear fit."),
    ("liver_GSE14323_HSF2_by_group.png", "S3", "GSE14323 (liver): HSF2 expression across "
     "disease groups (Normal, cirrhosis, cirrhosisHCC, HCC)."),
    ("liver_GSE14323_HSF2_vs_NETcore.png", "S4", "GSE14323 (liver, diseased subset, n=96): "
     "HSF2 vs. NET_core score scatter plot, colored by tissue group."),
    ("lung_GSE47460_HSF2_by_group.png", "S5", "GSE47460 (lung): HSF2 expression across "
     "disease groups (Control, COPD, other ILD, UIP/IPF)."),
    ("lung_GSE47460_HSF2_vs_NETcore.png", "S6", "GSE47460 (lung, UIP/IPF subset, n=122): "
     "HSF2 vs. NET_core score scatter plot with linear fit."),
    ("lung_GSE53845_HSF2_by_group.png", "S7", "GSE53845 (lung): HSF2 expression, control vs. "
     "IPF."),
    ("lung_GSE53845_HSF2_vs_NETcore.png", "S8", "GSE53845 (lung, IPF subset, n=40): HSF2 vs. "
     "NET_core score scatter plot with linear fit."),
    ("hcc_ICI_GSE215011_HSF2_by_response.png", "S9", "GSE215011 (HCC, anti-PD-1 monotherapy): "
     "HSF2 expression, responder vs. non-responder."),
    ("hcc_ICI_GSE215011_NETcore_by_response.png", "S10", "GSE215011 (HCC, anti-PD-1 "
     "monotherapy): NET_core score, responder vs. non-responder."),
    ("hcc_ICI_GSE215011_HSF2_vs_NETcore.png", "S11", "GSE215011 (HCC, n=10): HSF2 vs. "
     "NET_core score scatter plot, colored by ICI response."),
    ("hcc_ICI_GSE279750_HSF2_by_response.png", "S12", "GSE279750 (HCC, anti-PD-L1 "
     "combination, post-treatment): HSF2 expression, responder vs. non-responder."),
    ("hcc_ICI_GSE279750_HSF2_vs_NETcore.png", "S13", "GSE279750 (HCC, n=10): HSF2 vs. "
     "NET_core score scatter plot, colored by ICI response."),
    ("hcc_ICI_GSE235863_HSF2_by_response.png", "S14", "GSE235863 (HCC, anti-PD-1+lenvatinib "
     "combination, post-treatment): HSF2 expression, responder vs. non-responder."),
    ("hcc_ICI_GSE235863_HSF2_vs_NETcore.png", "S15", "GSE235863 (HCC, n=15): HSF2 vs. "
     "NET_core score scatter plot, colored by ICI response."),
]

for fname, label, desc in sfigs:
    add_figure(os.path.join(FIG, fname), width_in=5.0)
    add_caption(desc, bold_prefix=f"Figure {label}. ")

doc.save(OUT)
print(f"Supplementary Materials build complete: {OUT}")
print(f"Total paragraphs: {len(doc.paragraphs)}, tables: {len(doc.tables)}")
